"""esquema inicial

Revision ID: 626632a7cdc4
Revises: 
Create Date: 2026-07-21 22:24:20.925439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '626632a7cdc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supermercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listacompra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('supermercado_id', sa.Integer(), nullable=True),
    sa.Column('cerrada', sa.Boolean(), nullable=False),
    sa.Column('pagada', sa.Boolean(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['supermercado_id'], ['supermercado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemlistacompra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('lista_compra_id', sa.Integer(), nullable=True),
    sa.Column('precio_unidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['lista_compra_id'], ['listacompra.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listacomprapagador',
    sa.Column('lista_compra_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lista_compra_id'], ['listacompra.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('lista_compra_id', 'persona_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listacomprapagador')
    op.drop_table('itemlistacompra')
    op.drop_table('listacompra')
    op.drop_table('supermercado')
    op.drop_table('producto')
    op.drop_table('persona')
    # ### end Alembic commands ###
